version: 1.0.{build}

# https://www.appveyor.com/docs/build-configuration/
# https://www.appveyor.com/docs/build-environment/
# https://www.appveyor.com/docs/build-configuration/#specializing-matrix-job-configuration
# https://www.appveyor.com/docs/appveyor-yml/

image:
  - Visual Studio 2019

  - Visual Studio 2022

  - Ubuntu2004

  - macOS
skip_commits:
  files:
    - docs/*
    - media/*
  message: /updated readme.*|update readme.*s/
build: off

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
  init:
    - ps: $PSVersionTable
    # uncomment the line below to explore what modules/variables/env variables are available in the build image
    # - ps: Get-Module -ListAvailable; (Get-Variable).GetEnumerator() | Sort-Object Name | Out-String; (Get-ChildItem env:*).GetEnumerator() | Sort-Object Name | Out-String
    - ps: Install-PackageProvider -Name "NuGet" -Confirm:$false -Force -Verbose
    - ps: Install-Module -Name PowerShellGet -Repository PSGallery -Force
  install:
    - ps: . .\actions_bootstrap.ps1
  build_script:
    - ps: Invoke-Build -File .\src\AppVeyorVault.build.ps1

init:
  - pwsh: $PSVersionTable
  # uncomment the line below to explore what modules/variables/env variables are available in the build image
  # - pwsh: Get-Module -ListAvailable; (Get-Variable).GetEnumerator() | Sort-Object Name | Out-String; (Get-ChildItem env:*).GetEnumerator() | Sort-Object Name | Out-String
install:
  - pwsh: . .\actions_bootstrap.ps1
build_script:
  - pwsh: Invoke-Build -File .\src\AppVeyorVault.build.ps1

artifacts:
  - path: src/Artifacts/testOutput/PesterTests.xml
    name: PesterTestResults
  - path: src/Artifacts/ccReport/CodeCoverage.xml
    name: CodeCoverageResults
  - path: src/Archive/*.zip
    name: BuildArtifact

