version: 1.0.{build}

# https://www.appveyor.com/docs/build-configuration/
# https://www.appveyor.com/docs/build-configuration/#specializing-matrix-job-configuration

image:
  - Visual Studio 2017
  
  - Visual Studio 2019
  
  - Ubuntu1804
  
  - macOS
skip_commits:
  files:
    - docs/*
    - media/*
  message: /updated readme.*|update readme.*s/
build: off

for:
-
  matrix:
  only:
    - image: Visual Studio 2017
  init:
    - ps: $PSVersionTable
  install:
    - ps: . .\actions_bootstrap.ps1
  build_script:
    - ps: Invoke-Build -File .\src\AppVeyorTest.build.ps1

init:
  - pwsh: $PSVersionTable
  install:
    - pwsh: . .\actions_bootstrap.ps1
  build_script:
    - pwsh: Invoke-Build -File .\src\AppVeyorTest.build.ps1
