version: 1.0.{build}

# https://www.appveyor.com/docs/build-configuration/
# https://www.appveyor.com/docs/build-environment/
# https://www.appveyor.com/docs/build-configuration/#specializing-matrix-job-configuration
# https://www.appveyor.com/docs/appveyor-yml/

image:
  - Visual Studio 2017

  - Visual Studio 2019

  - Ubuntu1804

  - macOS
skip_commits:
  files:
    - docs/*
    - media/*
  message: /updated readme.*|update readme.*s/
build: off

for:
-
  matrix:
    only:
      - image: Visual Studio 2017
  init:
    - ps: $PSVersionTable
  install:
    - ps: . .\actions_bootstrap.ps1
  build_script:
    - ps: Remove-Module Pester -ErrorAction SilentlyContinue;Import-Module Pester -RequiredVersion 4.10.1;Invoke-Build -File .\src\AppVeyorTest.build.ps1

init:
  - pwsh: $PSVersionTable
install:
  - pwsh: . .\actions_bootstrap.ps1
build_script:
  - pwsh: Invoke-Build -File .\src\AppVeyorTest.build.ps1

artifacts:
  - path: src/Artifacts/testOutput/PesterTests.xml
    name: PesterTestResults
  - path: src/Artifacts/ccReport/CodeCoverage.xml
    name: CodeCoverageResults
  - path: src/Archive/*.zip
    name: BuildArtifact
